/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.trabalho.apresentacao;

import br.edu.ifnmg.trabalho.dados.DepartamentoDAO;
import br.edu.ifnmg.trabalho.dados.RelatorioDAO;
import br.edu.ifnmg.trabalho.dados.UsuarioDAO;
import br.edu.ifnmg.trabalho.entidade.Usuario;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Andre
 */
public class DiretorForm extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalForm
     */
    private Usuario usuario;

    public DiretorForm(Usuario usuario) {
        initComponents();
        UsuarioDAO usuarioDAO = new UsuarioDAO();
        this.usuario = usuarioDAO.info(usuario);
        lblUsuario.setText(usuario.getNome());
        lblTipo.setText("Cargo:" + usuario.getCargo());
        lblDepartamento.setText("NULL");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlInformacao = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDepartamento = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        itmCadDepartamento = new javax.swing.JMenuItem();
        itmGerente = new javax.swing.JMenuItem();
        itmEncarregado = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itmDadosDepartamento = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        itmListaEncarregado = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        itmDados = new javax.swing.JMenuItem();
        itmLogoff = new javax.swing.JMenuItem();
        itmSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Diretor");
        setExtendedState(6);

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("Usuario:");

        lblUsuario.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N

        lblTipo.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("Departamento:");

        lblDepartamento.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N

        javax.swing.GroupLayout pnlInformacaoLayout = new javax.swing.GroupLayout(pnlInformacao);
        pnlInformacao.setLayout(pnlInformacaoLayout);
        pnlInformacaoLayout.setHorizontalGroup(
            pnlInformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacaoLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        pnlInformacaoLayout.setVerticalGroup(
            pnlInformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuBar1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(208, 30));

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/trabalho/icon/cadastro.png"))); // NOI18N
        jMenu2.setText("Cadastro");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        itmCadDepartamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        itmCadDepartamento.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        itmCadDepartamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/trabalho/icon/departamento.png"))); // NOI18N
        itmCadDepartamento.setText("Departamento");
        itmCadDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadDepartamentoActionPerformed(evt);
            }
        });
        jMenu2.add(itmCadDepartamento);

        itmGerente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        itmGerente.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        itmGerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/trabalho/icon/gerente.png"))); // NOI18N
        itmGerente.setText("Gerente");
        itmGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmGerenteActionPerformed(evt);
            }
        });
        jMenu2.add(itmGerente);

        itmEncarregado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        itmEncarregado.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        itmEncarregado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/trabalho/icon/gerente.png"))); // NOI18N
        itmEncarregado.setText("Encarregado");
        itmEncarregado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmEncarregadoActionPerformed(evt);
            }
        });
        jMenu2.add(itmEncarregado);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/trabalho/icon/dados.png"))); // NOI18N
        jMenu3.setText("Dados");
        jMenu3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        itmDadosDepartamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        itmDadosDepartamento.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        itmDadosDepartamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/trabalho/icon/departamento.png"))); // NOI18N
        itmDadosDepartamento.setText("Departamento");
        itmDadosDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmDadosDepartamentoActionPerformed(evt);
            }
        });
        jMenu3.add(itmDadosDepartamento);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/trabalho/icon/gerente.png"))); // NOI18N
        jMenuItem1.setText("Gerente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        itmListaEncarregado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        itmListaEncarregado.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        itmListaEncarregado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/trabalho/icon/gerente.png"))); // NOI18N
        itmListaEncarregado.setText("Encarregado");
        itmListaEncarregado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListaEncarregadoActionPerformed(evt);
            }
        });
        jMenu3.add(itmListaEncarregado);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/trabalho/icon/relatorio.png"))); // NOI18N
        jMenu4.setText("Relatorio");
        jMenu4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenu4.setHideActionText(true);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/trabalho/icon/relatorio.png"))); // NOI18N
        jMenuItem2.setText("Relatorio Projeto");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/trabalho/icon/opcao.png"))); // NOI18N
        jMenu1.setText("Opção");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        itmDados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itmDados.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        itmDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/trabalho/icon/dadosPessoais.png"))); // NOI18N
        itmDados.setText("Dados Pessoais");
        itmDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmDadosActionPerformed(evt);
            }
        });
        jMenu1.add(itmDados);

        itmLogoff.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        itmLogoff.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        itmLogoff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/trabalho/icon/logoff.png"))); // NOI18N
        itmLogoff.setText("Logoff");
        itmLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmLogoffActionPerformed(evt);
            }
        });
        jMenu1.add(itmLogoff);

        itmSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        itmSair.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        itmSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/trabalho/icon/jamembo-error.png"))); // NOI18N
        itmSair.setText("Sair");
        itmSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmSairActionPerformed(evt);
            }
        });
        jMenu1.add(itmSair);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlInformacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlInformacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itmSairActionPerformed

    private void itmLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmLogoffActionPerformed
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itmLogoffActionPerformed

    private void itmDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmDadosActionPerformed
        DadosPessoaisForm dadosPessoais = new DadosPessoaisForm(this.usuario);
        pnlPrincipal.add(dadosPessoais);
        dadosPessoais.setVisible(true);
    }//GEN-LAST:event_itmDadosActionPerformed

    private void itmCadDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadDepartamentoActionPerformed
        CadastroDepartamentoForm cadastroDepartamentoForm = new CadastroDepartamentoForm();
        pnlPrincipal.add(cadastroDepartamentoForm);
        cadastroDepartamentoForm.setVisible(true);
    }//GEN-LAST:event_itmCadDepartamentoActionPerformed

    private void itmGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmGerenteActionPerformed
        DepartamentoDAO departamentoDAO = new DepartamentoDAO();
        if (departamentoDAO.listaDepartamento().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Não possui departamento cadastrado!", "Erro", JOptionPane.WARNING_MESSAGE);
        } else {
            CadastroGerenteForm cadastroGerenteForm = new CadastroGerenteForm();
            pnlPrincipal.add(cadastroGerenteForm);
            cadastroGerenteForm.setVisible(true);
        }
    }//GEN-LAST:event_itmGerenteActionPerformed

    private void itmEncarregadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmEncarregadoActionPerformed
        DepartamentoDAO departamentoDAO = new DepartamentoDAO();
        if (departamentoDAO.listaDepartamento().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Não possui departamento cadastrado!", "Erro", JOptionPane.WARNING_MESSAGE);
        } else {
            CadastroEncarregadoForm cadastroEncarregadoForm = new CadastroEncarregadoForm();
            pnlPrincipal.add(cadastroEncarregadoForm);
            cadastroEncarregadoForm.setVisible(true);
        }
    }//GEN-LAST:event_itmEncarregadoActionPerformed

    private void itmDadosDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmDadosDepartamentoActionPerformed
        ListaDepartamentoForm departamentoForm = new ListaDepartamentoForm();
        pnlPrincipal.add(departamentoForm);
        departamentoForm.setVisible(true);
    }//GEN-LAST:event_itmDadosDepartamentoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ListaGerenteForm gerenteForm = new ListaGerenteForm();
        pnlPrincipal.add(gerenteForm);
        gerenteForm.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void itmListaEncarregadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListaEncarregadoActionPerformed
        ListaEncarregadoForm encarregadoForm = new ListaEncarregadoForm("DIRETOR");
        pnlPrincipal.add(encarregadoForm);
        encarregadoForm.setVisible(true);
    }//GEN-LAST:event_itmListaEncarregadoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try{
            String relatorio = System.getProperty("user.dir") + "/Relatorios/relatorioProjeto.jasper";
            
            //Criar a fonte de dados do JasperReport
            JRBeanCollectionDataSource fontedados = new JRBeanCollectionDataSource(new RelatorioDAO().listaRelatorio());
            
            //Gerar o relatorio
            JasperPrint relatorioGerado = JasperFillManager.fillReport(relatorio, null, fontedados);
            
            //Exibir Relatorio
            JasperViewer jasperViewer = new JasperViewer(relatorioGerado,false);
            jasperViewer.setVisible(true);
            
        }catch(JRException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmCadDepartamento;
    private javax.swing.JMenuItem itmDados;
    private javax.swing.JMenuItem itmDadosDepartamento;
    private javax.swing.JMenuItem itmEncarregado;
    private javax.swing.JMenuItem itmGerente;
    private javax.swing.JMenuItem itmListaEncarregado;
    private javax.swing.JMenuItem itmLogoff;
    private javax.swing.JMenuItem itmSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lblDepartamento;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlInformacao;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
