/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.trabalho.apresentacao;

import br.edu.ifnmg.trabalho.dados.UsuarioDAO;
import br.edu.ifnmg.trabalho.entidade.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Andre
 */
public class GerenteForm extends javax.swing.JFrame {

    /**
     * Creates new form GerenteForm
     */
    private Usuario usuario;
    public GerenteForm(Usuario usuario) {
        initComponents();
        UsuarioDAO usuarioDAO = new UsuarioDAO();
        this.usuario = usuarioDAO.info(usuario);
        lblUsuario.setText(this.usuario.getNome());
        lblTipo.setText(usuario.getCargo());
        lblDepartamento.setText(usuario.getDepartamento().getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInformacao = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDepartamento = new javax.swing.JLabel();
        pnlPrincipal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itmDadosPessoais = new javax.swing.JMenuItem();
        itmLogoff = new javax.swing.JMenuItem();
        itmSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itmCadEncarregado = new javax.swing.JMenuItem();
        itmCadProjeto = new javax.swing.JMenuItem();
        itmCadAtividade = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itmListEncarregado = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        itmRelatorioAtividade = new javax.swing.JMenu();
        itemRelatorioAtividade = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setExtendedState(6);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("Usuario:");

        lblUsuario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lblTipo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Departamento:");

        lblDepartamento.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout pnlInformacaoLayout = new javax.swing.GroupLayout(pnlInformacao);
        pnlInformacao.setLayout(pnlInformacaoLayout);
        pnlInformacaoLayout.setHorizontalGroup(
            pnlInformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacaoLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        pnlInformacaoLayout.setVerticalGroup(
            pnlInformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
            .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );

        jMenu1.setText("Opção");

        itmDadosPessoais.setText("Dados Pessoais");
        itmDadosPessoais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmDadosPessoaisActionPerformed(evt);
            }
        });
        jMenu1.add(itmDadosPessoais);

        itmLogoff.setText("Logoff");
        itmLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmLogoffActionPerformed(evt);
            }
        });
        jMenu1.add(itmLogoff);

        itmSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        itmSair.setText("Sair");
        itmSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmSairActionPerformed(evt);
            }
        });
        jMenu1.add(itmSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cadastro");

        itmCadEncarregado.setText("Encarregado");
        itmCadEncarregado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadEncarregadoActionPerformed(evt);
            }
        });
        jMenu2.add(itmCadEncarregado);

        itmCadProjeto.setText("Projeto");
        itmCadProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadProjetoActionPerformed(evt);
            }
        });
        jMenu2.add(itmCadProjeto);

        itmCadAtividade.setText("Atividade");
        itmCadAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadAtividadeActionPerformed(evt);
            }
        });
        jMenu2.add(itmCadAtividade);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Dados");

        itmListEncarregado.setText("Encarregado");
        itmListEncarregado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListEncarregadoActionPerformed(evt);
            }
        });
        jMenu3.add(itmListEncarregado);

        jMenuItem1.setText("Projetos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Atividades");
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        itmRelatorioAtividade.setText("Relatorio");

        itemRelatorioAtividade.setText(" Atividades de projeto");
        itemRelatorioAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRelatorioAtividadeActionPerformed(evt);
            }
        });
        itmRelatorioAtividade.add(itemRelatorioAtividade);

        jMenuBar1.add(itmRelatorioAtividade);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlInformacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlInformacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmDadosPessoaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmDadosPessoaisActionPerformed
        DadosPessoaisForm dadosPessoaisForm = new DadosPessoaisForm(usuario);
        pnlPrincipal.add(dadosPessoaisForm);
        dadosPessoaisForm.setVisible(true);
    }//GEN-LAST:event_itmDadosPessoaisActionPerformed

    private void itmLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmLogoffActionPerformed
        LoginForm form = new LoginForm();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itmLogoffActionPerformed

    private void itmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itmSairActionPerformed

    private void itmCadEncarregadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadEncarregadoActionPerformed
        CadastroEncarregadoForm cadastroEncarregadoForm = new CadastroEncarregadoForm();
        pnlPrincipal.add(cadastroEncarregadoForm);
        cadastroEncarregadoForm.setVisible(true);
    }//GEN-LAST:event_itmCadEncarregadoActionPerformed

    private void itmListEncarregadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListEncarregadoActionPerformed
        ListaEncarregadoForm encarregadoForm = new ListaEncarregadoForm("GERENTE");
        pnlPrincipal.add(encarregadoForm);
        encarregadoForm.setVisible(true);
    }//GEN-LAST:event_itmListEncarregadoActionPerformed

    private void itmCadProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadProjetoActionPerformed
        CadastroProjetoForm cadastroProjetoForm = new CadastroProjetoForm(this.usuario);
        pnlPrincipal.add(cadastroProjetoForm);
        cadastroProjetoForm.setVisible(true);
    }//GEN-LAST:event_itmCadProjetoActionPerformed

    private void itmCadAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadAtividadeActionPerformed
        CadastroAtividadeForm atividadeForm = new CadastroAtividadeForm(this.usuario);
        pnlPrincipal.add(atividadeForm);
        atividadeForm.setVisible(true);
    }//GEN-LAST:event_itmCadAtividadeActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ListaProjetoForm form = new ListaProjetoForm(this.usuario);
        pnlPrincipal.add(form);
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void itemRelatorioAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRelatorioAtividadeActionPerformed
        RelatorioAtivdadeProjetoForm ativdadeProjetoForm = new RelatorioAtivdadeProjetoForm(usuario);
        pnlPrincipal.add(ativdadeProjetoForm);
        ativdadeProjetoForm.setVisible(true);
    }//GEN-LAST:event_itemRelatorioAtividadeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemRelatorioAtividade;
    private javax.swing.JMenuItem itmCadAtividade;
    private javax.swing.JMenuItem itmCadEncarregado;
    private javax.swing.JMenuItem itmCadProjeto;
    private javax.swing.JMenuItem itmDadosPessoais;
    private javax.swing.JMenuItem itmListEncarregado;
    private javax.swing.JMenuItem itmLogoff;
    private javax.swing.JMenu itmRelatorioAtividade;
    private javax.swing.JMenuItem itmSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lblDepartamento;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlInformacao;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
